# Generated by Django 4.1.3 on 2022-11-06 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=30, verbose_name='Street Name')),
                ('city', models.CharField(default='', max_length=30)),
                ('adrs', models.CharField(default='', max_length=35)),
                ('zip_code', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True)),
                ('nbStudents', models.PositiveIntegerField(default=1)),
                ('email', models.EmailField(default='nom_du_groupe@xyz.com', max_length=100)),
                ('speciality', models.CharField(default='BI', max_length=50)),
                ('level', models.CharField(choices=[('L1', 'premiere annee'), ('L2', 'deuxieme annee'), ('L3', 'troisieme annee'), ('M1', 'premiere master'), ('M2', 'deuxieme master')], default='L1', max_length=20)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='listOfAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('motif', models.CharField(default='', max_length=100)),
                ('justification', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'ListOfAbs',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('nbHours', models.DecimalField(decimal_places=2, default=21.0, max_digits=4)),
                ('semester', models.IntegerField(choices=[('S1', 'premier semetre'), ('S2', 'deuxieme semestre')], default='S1')),
                ('coef', models.FloatField(default=1.0)),
                ('credit', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'Module',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('familyName', models.CharField(default='', max_length=70)),
                ('birthDay', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(default='example@xyz.com', max_length=100)),
                ('grade', models.CharField(choices=[('dr', 'doctorant'), ('rec', 'recrute'), ('dir', 'director'), ('prof', 'professor')], default='dr', max_length=100)),
                ('nbHours', models.DecimalField(decimal_places=2, default=21.0, max_digits=4)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'University',
            },
        ),
        migrations.CreateModel(
            name='TeacherModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2022)),
                ('nbHours', models.DecimalField(decimal_places=2, default=21.0, max_digits=4)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.teacher')),
            ],
            options={
                'db_table': 'TeacherModules',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherModule',
            field=models.ManyToManyField(through='university_app.TeacherModules', to='university_app.module'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('familyName', models.CharField(default='', max_length=70)),
                ('birthDay', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(default='example@xyz.com', max_length=100)),
                ('photo', models.ImageField(upload_to='photos/students')),
                ('state', models.CharField(choices=[('pre', 'present student'), ('abs', 'absent student'), ('del', 'delayed student'), ('exc', 'excluded student')], default='pre', max_length=20)),
                ('situation', models.CharField(choices=[('new', 'new student'), ('rep', 'repeating student'), ('dero', 'derogatory student'), ('oth', 'other student')], default='new', max_length=20)),
                ('adrs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university_app.address')),
                ('grp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_app.group')),
                ('univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.university')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='study',
            field=models.ManyToManyField(to='university_app.module'),
        ),
    ]
