# Generated by Django 4.1.3 on 2022-11-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.CharField(choices=[('S1', 'premier semetre'), ('S2', 'deuxieme semestre')], default='S1', max_length=150),
        ),
    ]
